name: Deploy on approved PR

on:
  pull_request_review:
    types: [approved]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Deploy changes
        uses: docker://cumulussci/cumulusci:'3.75.1'
        with:
          entrypoint: bash
          args: -c "cci flow run deploy -o 'flow_name=MyDeployFlow' -o 'org=packaging'"